import {
  BarChart3,
  Bell,
  Bot,
  Boxes,
  Check,
  Database,
  FileText,
  Globe,
  Heart,
  KeyRound,
  Languages,
  Lock,
  MessageCircle,
  Package,
  Rocket,
  Search,
  Server,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Target,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { HomeIcon } from '@sellora/shared';

/** Icons the home page editor offers. The names are stored in the database; the components live here. */
export const HOME_ICON_MAP: Record<HomeIcon, LucideIcon> = {
  message: MessageCircle,
  sparkles: Sparkles,
  database: Database,
  server: Server,
  shield: ShieldCheck,
  target: Target,
  package: Package,
  boxes: Boxes,
  file: FileText,
  chart: BarChart3,
  bell: Bell,
  users: Users,
  lock: Lock,
  key: KeyRound,
  globe: Globe,
  bot: Bot,
  check: Check,
  zap: Zap,
  search: Search,
  languages: Languages,
  cart: ShoppingCart,
  heart: Heart,
  star: Star,
  rocket: Rocket,
};
